### ISSUE TITLE
Win8ScreenDriverImpl can't be successfully initialized

### ISSUE THREAD

**Issue by tiagocunico** [MindShow/USBDisplay#6]
Hello, it works normally until I connect my 3 monitor on my normal HDMI output. I was looking on the logs and apparently the problem is the way It's using the Win8ScreenDriverImpl.

This is the log i received, i [linked](https://github.com/MindShow/USBDisplay/files/6879990/WinUsbDisplay.log) the full log too.
> [18300/ 9812] 2021-07-26 13:50:21:111 ! Win8ScreenDriverImpl Catched Exception in the Win8ScreenDriverImpl::execute() function: Unable get all DXGI outputs for virtual screen. The exception will consider as critical
[18300/ 9812] 2021-07-26 13:50:21:212 ! Win8ScreenDriverImpl has an invalid state. The invalid state can be a part of screen propery changes. An update signal will be generated as a screen size changed signal.

i got this code [here](https://github.com/skbkontur/KonturVNC/blob/master/desktop/Win8ScreenDriverImpl.cpp), i suppose It's something close to the problem I'm facing.
> // Check that all outputs for the virtual screen are found (in case two or more
  // hardware graphic interfaces are used). It's better to avoid using buggy
  // Desktop Duplication API here rather than getting the wrong framebuffer.
  Screen screen;
  if (screen.getVisibleMonitorCount() != dxgiOutputArray.size()) {
    throw Exception(_T("Unable get all DXGI outputs for virtual screen"));
  }

if you have any idea what is happening, or how can I fix it, let me know. currently, I'm unable to use the adapter. 

thanks for your attention.

**Comment by MindShow** [comment]
thanks for your feedback，will you please send more infomation：
systerm information，export by dxdiag.exe



刘崇硕   Super  
------------------------------
优森美科技开发有限公司 
Ultrasemi Technology Development Co., Ltd. 
地址：深圳市宝安区航城大道塘东光电研发总部大厦1栋611-612 
Mob：18603000963  QQ：2272715136 
Tel：0755-85241830 Fax：0755-85241830 
***@***.***
 
From: tiagocunico
Date: 2021-07-27 01:06
To: MindShow/USBDisplay
CC: Subscribed
Subject: [MindShow/USBDisplay] Win8ScreenDriverImpl can't be successfully initialized (#6)
Hello, it works normally until I connect my 3 monitor on my normal HDMI output. I was looking on the logs and apparently the problem is the way It's using the Win8ScreenDriverImpl.
This is the log i received, i linked the full log too.
[18300/ 9812] 2021-07-26 13:50:21:111 ! Win8ScreenDriverImpl Catched Exception in the Win8ScreenDriverImpl::execute() function: Unable get all DXGI outputs for virtual screen. The exception will consider as critical
[18300/ 9812] 2021-07-26 13:50:21:212 ! Win8ScreenDriverImpl has an invalid state. The invalid state can be a part of screen propery changes. An update signal will be generated as a screen size changed signal.
i got this code here, i suppose It's something close to the problem I'm facing.
// Check that all outputs for the virtual screen are found (in case two or more
// hardware graphic interfaces are used). It's better to avoid using buggy
// Desktop Duplication API here rather than getting the wrong framebuffer.
Screen screen;
if (screen.getVisibleMonitorCount() != dxgiOutputArray.size()) {
throw Exception(_T("Unable get all DXGI outputs for virtual screen"));
}
if you have any idea what is happening, or how can I fix it, let me know. currently, I'm unable to use the adapter.
thanks for your attention.

**Comment by tiagocunico** [comment]
[Here](https://github.com/MindShow/USBDisplay/files/6887388/dx.txt) is the extra information. Hope its helpful :)

**Comment by tiagocunico** [comment]
Thanks for actualizing the driver, but I still have the same problem.
[Here](https://github.com/MindShow/USBDisplay/files/7943769/WinUsbDisplay.log) are the logs. 
I tried the @easternDay suggestion but it didn't work :(
